import sys,os
sys.path.append(os.path.abspath('..'),),

from django.core.management import setup_environ 
import settings 
setup_environ(settings),

from utils.django_mailman.models import List
lists = [
   List(name='Admin-l',public=True),
   List(name='Alumni',public=True),
   List(name='Amp-l'),
   List(name='Archive-l'),
   List(name='Boneyard'),
   List(name='Caffeine-l'),
   List(name='Chair-l'),
   List(name='Chapters-l'),
   List(name='chippc-l'),
   List(name='Cityhall-l'),
   List(name='Cluster-l'),
   List(name='Codeclub'),
   List(name='Conf-backup-l'),
   List(name='Conference'),
   List(name='Corporate-l'),
   List(name='Cyberdefense-l'),
   List(name='ECS-Ambassadors-L'),
   List(name='Eoh-l'),
   List(name='Exec',public=True),
   List(name='Exec-announce',public=True),
   List(name='Film-l',public=True),
   List(name='Food-l',public=True),
   List(name='Forsale-l'),
   List(name='Fss-l'),
   List(name='Gamebuilders',public=True),
   List(name='gb-dev',public=True),
   List(name='Gourmets-l'),
   List(name='Hackillinois-l'),
   List(name='h0l'),
   List(name='ICPC-l'),
   List(name='Init-l'),
   List(name='Jobs-l',public=True),
   List(name='Kweerie-l'),
   List(name='Logistics-c'),
   List(name='Logistics-l'),
   List(name='Lug-l',public=True),
   List(name='macdev-projects',public=True),
   List(name='MacWarriors',public=True),
   List(name='Mailman'),
   List(name='Mecheye-l'),
   List(name='Media-c'),
   List(name='Membership-l',public=True),
   List(name='Minecraft-l',public=True),
   List(name='mm-help'),
   List(name='mm-l'),
   List(name='Mm9-l'),
   List(name='Mmx-l'),
   List(name='Oldtop4'),
   List(name='Ourcade-l'),
   List(name='Outreach'),
   List(name='Puzzlecrack-l'),
   List(name='Puzzlehack-l'),
   List(name='Puzzlehack2'),
   List(name='Quadday-l'),
   List(name='Ringcycle-l'),
   List(name='Riverweb-l'),
   List(name='Rp03-guest-l'),
   List(name='scavenger-l'),
   List(name='Seattle-l'),
   List(name='Secretary-l'),
   List(name='SIGACT-l',public=True),
   List(name='SIGArch-l',public=True),
   List(name='SIGArt-l',public=True),
   List(name='SIGBio-l',public=True),
   List(name='SIGBot',public=True),
   List(name='SIGCHI-l',public=True),
   List(name='SIGDave-l',public=True),
   List(name='Sigeducation-l',public=True),
   List(name='SIGEmbedded-l',public=True),
   List(name='SIGGRAPH-Announce',public=True),
   List(name='SIGGRAPH-l',public=True),
   List(name='SIGKDD-l',public=True),
   List(name='SIGMation-l',public=True),
   List(name='SIGMil-l',public=True),
   List(name='SIGMis-l',public=True),
   List(name='SIGMobile-l',public=True),
   List(name='SIGMusic-l',public=True),
   List(name='SIGNet-l',public=True),
   List(name='SIGOps-l',public=True),
   List(name='SIGPLAN-l',public=True),
   List(name='SIGPony-l',public=True),
   List(name='SIGSAC-L',public=True),
   List(name='SIGSoft-l',public=True),
   List(name='SIGUnix-l',public=True),
   List(name='SIGWin-l',public=True),
   List(name='sls-l',public=True),
   List(name='Social-l'),
   List(name='Speakers-c'),
   List(name='speakers-l'),
   List(name='Summer-l',public=True),
   List(name='sv-l'),
   List(name='Test-l'),
   List(name='Toaru-l'),
   List(name='top4'),
   List(name='Treasurer-l'),
   List(name='TW2002-l'),
   List(name='UBD-l'),
   List(name='Vice-chair-l'),
   List(name='Volunteers-c'),
   List(name='Watchdogs-l'),
   List(name='Web-c'),
   List(name='Webmonkeys-l',public=True),
   List(name='Website-l'),
]

for l in lists:
   try:
      l.save()
   except:
      print "error adding %s"%l

print "done"